### PR TITLE
Adding of get request array params support 

### PR DESCRIPTION
**Pull request by roychoo**
was trying to have array params in the query 
```
"query" : {
  "pages": ["page", "page2"]
}
```
thus, submitting this PR to have this functionality.
let me know if it is ok

### CODE REVIEW

**Comment by daxsorbito** [comment]
:+1:  for this

**Comment by basicallydan** [comment]
Ooh that sounds like a good idea. Currently on a bus rolling down a winding
road in Northern Thailand, would be probably quite uncomfortable to try it
out. I'll have a look when I get to a hotel in the next few hours.

Thanks for the PR!

**Comment by basicallydan** [comment]
Also thanks for writing tests!

**Comment by roychoo** [comment]
np, let me know if you need me to change anything.

**Comment by basicallydan** [comment]
Hey @roychoo thanks for your wonderful pull request. I did add one thing out of sheer paranoia, and made two small changes out of being a little anal about style:

1. Replaced `"` with `'`
2. Added a test to make sure old-school array queryparam syntax (`pages[]=1&pages[]=2`) worked
3. Put the array test (now tests thanks to me) into a `desc` block for organisational purposes mainly because there are two now.

Anyway, your PR was textbook. Nice work, and thanks. You're now in the contributors list in readme.md. Thank you @daxsorbito for the support too :+1: 

Also I fixed a test which broke due to the advent of Node 5.0.

**Pull request merged**
